[build]
  # Indica dónde están los archivos compilados de Angular
  publish = "dist/notes-app"
  # Directorio donde se encuentran las funciones de Netlify
  functions = ".netlify/functions"

[dev]
  # Puerto para la simulación local de funciones
  functionsPort = 9999
